<template>
  <div>
    100 以下
    <table border="1" cellpadding="0" cellspacing="0" style="width: 100%;">
      <tbody>
        <tr>
          <td>
            <p>0</p>
          </td>
          <td>れい、ぜろ</td>
          <td>
            <p>10</p>
          </td>
          <td>
            <p>じゅう</p>
          </td>
          <td>
            <p>20</p>
          </td>
          <td>
            <p>にじゅう</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>1</p>
          </td>
          <td>いち</td>
          <td>
            <p>11</p>
          </td>
          <td>
            <p>じゅういち</p>
          </td>
          <td>
            <p>30</p>
          </td>
          <td>
            <p>さんじゅう</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>2</p>
          </td>
          <td>
            <p>に</p>
          </td>
          <td>
            <p>12</p>
          </td>
          <td>
            <p>じゅうに</p>
          </td>
          <td>
            <p>40</p>
          </td>
          <td>
            <p>よんじゅう</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>3</p>
          </td>
          <td>
            <p>さん</p>
          </td>
          <td>
            <p>13</p>
          </td>
          <td>
            <p>じゅうさん</p>
          </td>
          <td>
            <p>50</p>
          </td>
          <td>ごじゅう</td>
        </tr>
        <tr>
          <td>
            <p>4</p>
          </td>
          <td>
            <p>し、よん</p>
          </td>
          <td>
            <p>14</p>
          </td>
          <td>
            <p>じゅうし、じゅうよん</p>
          </td>
          <td>
            <p>60</p>
          </td>
          <td>
            <p>ろくじゅう</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>5</p>
          </td>
          <td>
            <p>ご</p>
          </td>
          <td>
            <p>15</p>
          </td>
          <td>
            <p>じゅうご</p>
          </td>
          <td>
            <p>70</p>
          </td>
          <td>
            <p>ななじゅう</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>6</p>
          </td>
          <td>
            <p>ろく</p>
          </td>
          <td>
            <p>16</p>
          </td>
          <td>
            <p>じゅうろく</p>
          </td>
          <td>
            <p>80</p>
          </td>
          <td>
            <p>はちじゅう</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>7</p>
          </td>
          <td>しち、なな</td>
          <td>
            <p>17</p>
          </td>
          <td>
            <p>じゅうしち、じゅうなな</p>
          </td>
          <td>
            <p>90</p>
          </td>
          <td>
            <p>きゅうじゅう</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>8</p>
          </td>
          <td>
            <p>はち</p>
          </td>
          <td>
            <p>18</p>
          </td>
          <td>
            <p>じゅうはち</p>
          </td>
          <td>
            <p>100</p>
          </td>
          <td>
            <p>ひゃく</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>9</p>
          </td>
          <td>
            <p>く、きゅう</p>
          </td>
          <td>
            <p>19</p>
          </td>
          <td>
            <p>じゅうく、じゅうきゅう</p>
          </td>
          <td colspan="2" rowspan="2">
            <p mce_keep="true">&nbsp;</p>
            <p mce_keep="true">&nbsp;</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>0.1</p>
          </td>
          <td>
            <p>れいてんいち</p>
          </td>
          <td>
            <p>2/3</p>
          </td>
          <td>
            <p>さんぶんのに</p>
            <div>&nbsp;</div>
          </td>
        </tr>
      </tbody>
    </table>100 以上
    <table border="1" cellpadding="0" cellspacing="0" style="width: 100%;">
      <tbody>
        <tr>
          <td>
            <p>100</p>
          </td>
          <td>ひゃく</td>
          <td>
            <p>1000</p>
          </td>
          <td>
            <p>せん</p>
          </td>
          <td>
            <p>10，000</p>
          </td>
          <td>いちまん</td>
        </tr>
        <tr>
          <td>
            <p>200</p>
          </td>
          <td>
            <p>にひゃく</p>
          </td>
          <td>
            <p>2000</p>
          </td>
          <td>
            <p>にせん</p>
          </td>
          <td>
            <p>100，000</p>
          </td>
          <td>
            <p>じゅうまん</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>300</p>
          </td>
          <td>
            <p>さんびゃく</p>
          </td>
          <td>
            <p>3000</p>
          </td>
          <td>
            <p>さんぜん</p>
          </td>
          <td>
            <p>1，000，000</p>
          </td>
          <td>
            <p>ひゃくまん</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>400</p>
          </td>
          <td>
            <p>よんひゃく</p>
          </td>
          <td>
            <p>4000</p>
          </td>
          <td>
            <p>よんせん</p>
          </td>
          <td>
            <p>10，000，000</p>
          </td>
          <td>
            <p>いっせんまん</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>500</p>
          </td>
          <td>
            <p>ごひゃく</p>
          </td>
          <td>
            <p>5000</p>
          </td>
          <td>
            <p>ごせん</p>
          </td>
          <td>
            <p>100，000，000</p>
          </td>
          <td>
            <p>いちおく</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>600</p>
          </td>
          <td>
            <p>ろっぴゃく</p>
          </td>
          <td>
            <p>6000</p>
          </td>
          <td>
            <p>ろくせん</p>
          </td>
          <td>
            <p>9002</p>
          </td>
          <td>きゅうせんに</td>
        </tr>
        <tr>
          <td>
            <p>700</p>
          </td>
          <td>
            <p>ななひゃく</p>
          </td>
          <td>
            <p>7000</p>
          </td>
          <td>
            <p>ななせん</p>
          </td>
          <td>
            <p>9020</p>
          </td>
          <td>
            <p>きゅうせんにじゅう</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>800</p>
          </td>
          <td>
            <p>はっぴゃく</p>
          </td>
          <td>
            <p>8000</p>
          </td>
          <td>
            <p>はっせん</p>
          </td>
          <td>
            <p>9200</p>
          </td>
          <td>
            <p>きゅうせんにひゃく</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>900</p>
          </td>
          <td>
            <p>きゅうひゃく</p>
          </td>
          <td>
            <p>9000</p>
          </td>
          <td colspan="3" rowspan="1">
            <p>きゅうせん</p>
            <div>&nbsp;</div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</template>
